### ISSUE TITLE
Return authinfo_unavail when there's not connection to the server

### ISSUE THREAD

**Issue by ghost** [rmbreak/pam_ldapdb#3]
It would be nice if this module returns `authinfo_unavail` when there's no connection to the server. Doing so using it with `pam_ccreds` would be easier/cleaner.

Currently `auth_err` is returned always, therefore it's hard to distinguish what went wrong.

What do you think about it @rmbreak ?
If you're OK with it, I'd implement it and send a pull request.

**Comment by smackysnacks** [comment]
@rleitner I strongly agree. A PR would be most welcomed.
